// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    dependencies {
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.4.10'
    }
}

plugins {
    id 'com.android.application' version '9.4.0' apply false
}



task clean(type: Delete) {
    delete rootProject.buildDir
}
