package com.unhappychoice.norimaki.model

import java.util.*

data class Build(
  val compare: String,
  val committerDate: String,
  val steps: List<BuildStep>,
  val body: String,
  val usageQueuedAt: Date,
  val retryOf: Int,
  val reponame: String,
  val buildUrl: String,
  val failed: Boolean,
  val branch: String,
  val username: String,
  val authorDate: String,
  val why: String,
  val user: Map<String, Any>,
  val vcsRevision: String,
  val vcsTag: String,
  val buildNum: Int,
  val infrastructureFail: Boolean,
  val committerEmail: String,
  val previous: Map<String, Any>,
  val status: String,
  val committerName: String,
  val retries: List<Int>,
  val subject: String,
  val timedout: Boolean,
  val dontBuild: Boolean,
  val lifecycle: String,
  val stopTime: Date,
  val buildTimeMillis: Int,
  val circleYml: Map<String, Any>,
  val messages: List<String>,
  val isFirstGreenBuild: Boolean,
  val jobName: String,
  val startTime: Date,
  val canceler: String,
  val allCommitDetails: List<Commit>,
  val outcome: String,
  val vcsUrl: String,
  val authorName: String,
  val queuedAt: Date,
  val canceled: Boolean,
  val authorEmail: String
)
